import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import'./styles.css';
const pages={HOME:'101',MUSIC:'102',LIVE:'103',EPK:'104',CONTACT:'105'};
const releases=[{title:'UNDER THE WATER',type:'Single',year:'2026',art:'UW',link:'https://velvetbandglasgow.bandcamp.com/album/under-the-water'}];
const gigs=[['01 OCT',"Nice 'n' Sleazy's",'GLASGOW','https://www.eventbrite.ca/e/thomas-duxbury-eyes-of-home-velvet-glasgow-nice-n-sleazy-tickets-1994096886467']];
function App(){const[page,setPage]=useState('HOME');const[time,setTime]=useState(new Date());useEffect(()=>{const i=setInterval(()=>setTime(new Date()),1000);return()=>clearInterval(i)},[]);
const goto=p=>setPage(p);const pageNo=pages[page];const day=time.toLocaleDateString('en-GB',{weekday:'short',day:'2-digit',month:'short',year:'numeric'});const clock=time.toLocaleTimeString('en-GB',{hour12:false});
return <div className="crt"><header><div className="topline"><span>100</span><span>VELVET 100</span><span>{day}</span><strong>{clock}</strong><span className="grow"/><span>GLASGOW</span><b>16°C</b><span>☀</span></div><div className="head"><div className="logo">VELVET</div><nav>{Object.entries(pages).map(([k,n])=><button key={k} className={page===k?'active':''} onClick={()=>goto(k)}><i>{n}</i> {k}</button>)}</nav></div></header>
<main>
{page==='HOME'&&<Home goto={goto}/>}
{page==='MUSIC'&&<Music/>}
{page==='LIVE'&&<Live/>}
{page==='EPK'&&<EPK/>}
{page==='CONTACT'&&<Contact/>}
</main>
<footer><span>VELVET</span><span>:::</span><span>COME HOME — OUT NOW</span><span>:::</span><span>GLASGOW</span><span>:::</span><span>MUSIC</span><span>:::</span><span>LIVE</span><span>:::</span><span>CONTACT</span><span>:::</span><span>VELVET</span></footer>
</div>}
function Bar({no,title,children}){return <section><div className="bar"><span>{no} {title}</span><span>1/1</span></div>{children}</section>}
function Home({goto}){return <div className="grid home"><div className="left"><Bar no="101" title="HOME"><div className="hero"><div className="halftone"><div className="photoPlaceholder">VELVET<br/><small>BAND PHOTO</small></div></div><div className="heroText"><small>NEW SINGLE</small><h1>COME HOME</h1><h2>COMING SOON</h2><p>NEW MUSIC FROM VELVET — GLASGOW</p></div></div></Bar><Bar no="" title="LISTEN NOW"><div className="listen"><div className="cover">UW</div><div><strong>UNDER THE WATER</strong><small>Velvet · Single · 2026</small><div className="track">▶ <span></span></div></div><div className="services"><a href="https://open.spotify.com/artist/45dG1NWjvFA9SkPLICjGr8?si=TgCGkMzGTTGLDGyVBn7E4w&utm_source=copy-link" target="_blank">◉ SPOTIFY</a><button>♫ APPLE MUSIC</button><a href="https://velvetbandglasgow.bandcamp.com/album/under-the-water" target="_blank">bc BANDCAMP</a></div></div></Bar><Bar no="" title="SOCIALS"><div className="socials"><a href="https://www.instagram.com/velvetgla/" target="_blank">◎ INSTAGRAM</a><a href="https://www.tiktok.com/@velvetgla" target="_blank">♪ TIKTOK</a><a href="https://www.facebook.com/share/19bMxvLLCw/" target="_blank">● FACEBOOK</a><a href="https://x.com/velvetbandgla" target="_blank">𝕏 X</a><a href="https://open.spotify.com/artist/45dG1NWjvFA9SkPLICjGr8?si=TgCGkMzGTTGLDGyVBn7E4w&utm_source=copy-link" target="_blank">◉ SPOTIFY</a></div></Bar></div><div className="right"><Bar no="102" title="MUSIC"><MiniMusic/></Bar><Bar no="103" title="LIVE"><div className="upcoming">{gigs.map(g=><div className="gig" key={g[0]}><b>{g[0]}</b><span>{g[1]}<small>GLASGOW</small></span><a href={g[3]} target="_blank">TICKETS</a></div>)}</div></Bar><Bar no="104" title="PRESS / EPK"><div className="epkMini"><div><h3>ABOUT VELVET</h3><p>Velvet are back with “Under the Water”, an emotional slow-rocker exploring insecurity, loss and desperation inside a raw, riff-laden pop song.</p><p className="quote">“Soulful and Menacing” — Snack Magazine</p><p className="quote">“A Promising Bright Spot in Scotland’s Rock Scene” — Atwood Magazine</p><a onClick={()=>goto('EPK')}>READ FULL BIO 104 &gt;</a></div><div><h3>QUICK LINKS</h3><p>■ Short bio<br/>■ Long bio<br/>■ Press photos<br/>■ Logos<br/>■ Selected press quotes<br/>■ Previous notable shows<br/>■ Tech rider</p></div></div></Bar><Bar no="105" title="CONTACT"><div className="contactMini"><div><h3>BOOKING & ENQUIRIES</h3><p><a href="mailto:velvetbandglasgow@gmail.com">velvetbandglasgow@gmail.com</a></p></div><div><h3>FOLLOW</h3><p>◎　♪　●　𝕏　◉</p></div></div></Bar></div></div>}
function MiniMusic(){return <div>{releases.map((r,i)=><div className="release mini" key={r.title}><div className={'cover c'+i}>{r.art}</div><div><strong>{r.title}</strong><small>{r.type} · {r.year}</small><p>{r.link?'BANDCAMP':'COMING SOON'}</p></div><b>0{i+1}</b></div>)}</div>}
function Music(){return <div className="single"><Bar no="102" title="MUSIC"><div className="releaseList">{releases.map((r,i)=><div className="release" key={r.title}><div className={'cover c'+i}>{r.art}</div><div><h2>{r.title}</h2><small>{r.type} · {r.year}</small><p>SPOTIFY　|　APPLE MUSIC　|　BANDCAMP</p></div></div>)}</div></Bar></div>}
function Live(){return <div className="single"><Bar no="103" title="LIVE"><h2 className="yellow">UPCOMING GIGS</h2>{gigs.map(g=><div className="bigGig" key={g[0]}><b>{g[0]}</b><div><strong>{g[1]}</strong><small>{g[2]}</small></div><button>TICKETS</button></div>)}<hr/><h2 className="yellow">PAST SHOWS</h2><p>Audio / The Hug & Pint / Nice 'n' Sleazy's / King Tut's / Stag and Dagger / Endless Summer / Edinburgh Fringe Festival / + more</p></Bar></div>}
function EPK(){return <div className="single"><Bar no="104" title="PRESS / EPK"><div className="two"><div><h2 className="yellow">ABOUT VELVET</h2><p>Velvet are a Glasgow five-piece. Their forthcoming single “Under the Water” is an emotional slow-rocker exploring insecurity, loss and desperation inside a raw, riff-laden pop song.</p><p>The band have played a sold-out DIY headline show at Audio in Glasgow and festivals including Stag and Dagger, Endless Summer and the Edinburgh Fringe Festival. Their self-produced compilation EP <i>The Constant</i> closed an earlier chapter for the group.</p></div><div><h2 className="yellow">DOWNLOADS / INFO</h2><p>■ Short bio<br/>■ Long bio<br/>■ Press photos<br/>■ Logo pack<br/>■ Music links<br/>■ Previous notable shows<br/>■ Technical rider / stage plot</p><p className="quote">“A sophisticated and unique sound” — Discovery Music</p></div></div></Bar></div>}
function Contact(){return <div className="single"><Bar no="105" title="CONTACT"><div className="two"><div><h2 className="yellow">BOOKING</h2><p className="bigEmail"><a href="mailto:velvetbandglasgow@gmail.com">velvetbandglasgow@gmail.com</a></p><h2 className="yellow">GENERAL ENQUIRIES</h2><p className="bigEmail"><a href="mailto:velvetbandglasgow@gmail.com">velvetbandglasgow@gmail.com</a></p></div><div><h2 className="yellow">FOLLOW</h2><p><a href="https://www.instagram.com/velvetgla/" target="_blank">INSTAGRAM</a><br/><a href="https://www.tiktok.com/@velvetgla" target="_blank">TIKTOK</a><br/><a href="https://www.facebook.com/share/19bMxvLLCw/" target="_blank">FACEBOOK</a><br/><a href="https://x.com/velvetbandgla" target="_blank">X / TWITTER</a><br/><a href="https://open.spotify.com/artist/45dG1NWjvFA9SkPLICjGr8" target="_blank">SPOTIFY</a><br/><a href="https://velvetbandglasgow.bandcamp.com/album/under-the-water" target="_blank">BANDCAMP</a></p></div></div></Bar></div>}
createRoot(document.getElementById('root')).render(<App/>);