import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import'./styles.css';
const pages={HOME:'101',MUSIC:'102',LIVE:'103',EPK:'104',CONTACT:'105'};
const releases=[{title:'UNDER THE WATER',type:'Single',year:'2026',art:'UW',link:'https://velvetbandglasgow.bandcamp.com/album/under-the-water'}];
const gigs=[['01 OCT',"Nice 'n' Sleazy's",'GLASGOW','https://www.eventbrite.ca/e/thomas-duxbury-eyes-of-home-velvet-glasgow-nice-n-sleazy-tickets-1994096886467']];
function pathToPage(path){const p=path.replace(/\/$/,'')||'/';return p==='/'?'HOME':p==='/music'?'MUSIC':p==='/live'?'LIVE':p==='/epk'?'EPK':p==='/contact'?'CONTACT':'HOME'}
function pageToPath(p){return p==='HOME'?'/' : `/${p.toLowerCase()}`}
function App(){const[page,setPage]=useState(()=>pathToPage(window.location.pathname));const[time,setTime]=useState(new Date());useEffect(()=>{const onPop=()=>setPage(pathToPage(window.location.pathname));window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop)},[]);useEffect(()=>{const i=setInterval(()=>setTime(new Date()),1000);return()=>clearInterval(i)},[]);
const goto=p=>{const path=pageToPath(p);if(window.location.pathname!==path)window.history.pushState({},'',path);setPage(p)};const pageNo=pages[page];const day=time.toLocaleDateString('en-GB',{weekday:'short',day:'2-digit',month:'short',year:'numeric'});const clock=time.toLocaleTimeString('en-GB',{hour12:false});
return <div className="crt"><header><div className="topline"><span>100</span><span>VELVET 100</span><span>{day}</span><strong>{clock}</strong><span className="grow"/><span>GLASGOW</span><b>16°C</b><span>☀</span></div><div className="head"><div className="logo">VELVET</div><nav>{Object.entries(pages).map(([k,n])=><button key={k} className={page===k?'active':''} onClick={()=>goto(k)}><i>{n}</i> {k}</button>)}</nav></div></header>
<main>
{page==='HOME'&&<Home goto={goto}/>}
{page==='MUSIC'&&<Music/>}
{page==='LIVE'&&<Live/>}
{page==='EPK'&&<EPK/>}
{page==='CONTACT'&&<Contact/>}
</main>
<footer><span>VELVET</span><span>:::</span><span>UNDER THE WATER — OUT NOW</span><span>:::</span><span>GLASGOW</span><span>:::</span><span>MUSIC</span><span>:::</span><span>LIVE</span><span>:::</span><span>CONTACT</span><span>:::</span><span>VELVET</span></footer>
</div>}
function Bar({no,title,children}){return <section><div className="bar"><span>{no} {title}</span><span>1/1</span></div>{children}</section>}
function Home({goto}){return <div className="single homePage"><Bar no="101" title="HOME"><div className="hero"><div className="halftone"><div className="photoPlaceholder">VELVET</div></div><div className="heroText"><small>VELVET</small><h1>UNDER THE WATER</h1><h2>OUT NOW</h2><p>NEW MUSIC FROM GLASGOW</p></div></div><div className="listen"><div className="cover">UW</div><div><strong>UNDER THE WATER</strong><small>Velvet · Single · 2026</small><div className="track">▶ <span></span></div></div><div className="services"><a href="https://open.spotify.com/artist/45dG1NWjvFA9SkPLICjGr8?si=TgCGkMzGTTGLDGyVBn7E4w&utm_source=copy-link" target="_blank">◉ SPOTIFY</a><a href="https://music.apple.com/gb/artist/velvet/657341158" target="_blank">♫ APPLE MUSIC</a><a href="https://velvetbandglasgow.bandcamp.com/album/under-the-water" target="_blank">bc BANDCAMP</a></div></div><div className="socials"><a href="https://www.instagram.com/velvetgla/" target="_blank">◎ INSTAGRAM</a><a href="https://www.tiktok.com/@velvetgla" target="_blank">♪ TIKTOK</a><a href="https://www.facebook.com/share/19bMxvLLCw/" target="_blank">● FACEBOOK</a><a href="https://x.com/velvetbandgla" target="_blank">𝕏 X</a></div></Bar></div>}
function MiniMusic(){return <div>{releases.map((r,i)=><div className="release mini" key={r.title}><div className={'cover c'+i}>{r.art}</div><div><strong>{r.title}</strong><small>{r.type} · {r.year}</small><p>{r.link?'BANDCAMP':'COMING SOON'}</p></div><b>0{i+1}</b></div>)}</div>}
function Music(){return <div className="single musicPage"><Bar no="102" title="MUSIC"><div className="featuredRelease compact"><div className="releaseArtwork"><div className="artFallback">UNDER<br/>THE<br/>WATER</div></div><div className="releaseInfo"><div className="featuredTag">FEATURED RELEASE</div><h1>UNDER THE WATER</h1><div className="releaseMeta">SINGLE · 01 MAY 2026 · VELVET</div><p className="releaseDescription">An emotional, slow-rocker exploring insecurity, loss and desperation inside a raw and riff-laden pop song.</p><div className="releaseLinks"><a href="https://open.spotify.com/artist/45dG1NWjvFA9SkPLICjGr8" target="_blank">◉ SPOTIFY</a><a href="https://music.apple.com/gb/artist/velvet/657341158" target="_blank">♫ APPLE MUSIC</a><a href="https://velvetbandglasgow.bandcamp.com/album/under-the-water" target="_blank">bc BANDCAMP</a></div></div></div><div className="olderReleases"><h2 className="yellow">PREVIOUS RELEASES</h2><div className="releaseRows"><div className="olderRelease"><div className="olderArt blackBlue">BLACK<br/>AND<br/>BLUE</div><div><h3>BLACK AND BLUE</h3><p>SINGLE · 2020</p><a href="https://open.spotify.com/artist/45dG1NWjvFA9SkPLICjGr8" target="_blank">SPOTIFY →</a><a href="https://music.apple.com/gb/artist/velvet/657341158" target="_blank">APPLE MUSIC →</a><a href="https://velvetbandglasgow.bandcamp.com/" target="_blank">BANDCAMP →</a></div></div><div className="olderRelease"><div className="olderArt prefer">I PREFER<br/>YOU</div><div><h3>I PREFER YOU (IN MY HEAD)</h3><p>SINGLE · 2022</p><a href="https://music.apple.com/us/album/i-prefer-you-in-my-head-single/1606984517" target="_blank">APPLE MUSIC →</a><a href="https://open.spotify.com/artist/45dG1NWjvFA9SkPLICjGr8" target="_blank">SPOTIFY →</a><a href="https://velvetbandglasgow.bandcamp.com/" target="_blank">BANDCAMP →</a></div></div></div></div><div className="playerBlock"><h2 className="yellow">LISTEN ON SPOTIFY</h2><iframe title="Velvet on Spotify" src="https://open.spotify.com/embed/artist/45dG1NWjvFA9SkPLICjGr8?utm_source=generator" width="100%" height="152" frameBorder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe></div></Bar></div>}
function Live(){return <div className="single"><Bar no="103" title="LIVE"><h2 className="yellow">UPCOMING GIGS</h2>{gigs.map(g=><div className="bigGig" key={g[0]}><b>{g[0]}</b><div><strong>{g[1]}</strong><small>{g[2]}</small></div><button>TICKETS</button></div>)}<hr/><h2 className="yellow">PAST SHOWS</h2><p>Audio / The Hug & Pint / Nice 'n' Sleazy's / King Tut's / Stag and Dagger / Endless Summer / Edinburgh Fringe Festival / + more</p></Bar></div>}
function EPK(){return <div className="single"><Bar no="104" title="PRESS / EPK"><div className="two"><div><h2 className="yellow">ABOUT VELVET</h2><p>Velvet are a Glasgow five-piece. Their forthcoming single “Under the Water” is an emotional slow-rocker exploring insecurity, loss and desperation inside a raw, riff-laden pop song.</p><p>The band have played a sold-out DIY headline show at Audio in Glasgow and festivals including Stag and Dagger, Endless Summer and the Edinburgh Fringe Festival. Their self-produced compilation EP <i>The Constant</i> closed an earlier chapter for the group.</p></div><div><h2 className="yellow">DOWNLOADS / INFO</h2><p>■ Short bio<br/>■ Long bio<br/>■ Press photos<br/>■ Logo pack<br/>■ Music links<br/>■ Previous notable shows<br/>■ Technical rider / stage plot</p><p className="quote">“A sophisticated and unique sound” — Discovery Music</p></div></div></Bar></div>}
function Contact(){return <div className="single"><Bar no="105" title="CONTACT"><div className="two"><div><h2 className="yellow">BOOKING</h2><p className="bigEmail"><a href="mailto:velvetbandglasgow@gmail.com">velvetbandglasgow@gmail.com</a></p><h2 className="yellow">GENERAL ENQUIRIES</h2><p className="bigEmail"><a href="mailto:velvetbandglasgow@gmail.com">velvetbandglasgow@gmail.com</a></p></div><div><h2 className="yellow">FOLLOW</h2><p><a href="https://www.instagram.com/velvetgla/" target="_blank">INSTAGRAM</a><br/><a href="https://www.tiktok.com/@velvetgla" target="_blank">TIKTOK</a><br/><a href="https://www.facebook.com/share/19bMxvLLCw/" target="_blank">FACEBOOK</a><br/><a href="https://x.com/velvetbandgla" target="_blank">X / TWITTER</a><br/><a href="https://open.spotify.com/artist/45dG1NWjvFA9SkPLICjGr8" target="_blank">SPOTIFY</a><br/><a href="https://velvetbandglasgow.bandcamp.com/album/under-the-water" target="_blank">BANDCAMP</a></p></div></div></Bar></div>}
createRoot(document.getElementById('root')).render(<App/>);