import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import'./styles.css';
const pages={HOME:'101',MUSIC:'102',LIVE:'103',EPK:'104',CONTACT:'105'};
const releases=[{title:'COME HOME',type:'Single',year:'2026',art:'CH'},{title:'UNDER THE WATER',type:'Single',year:'2026',art:'UW'},{title:'THE CONSTANT',type:'Compilation',year:'2024',art:'TC'}];
const gigs=[['03 OCT',"Nice 'n' Sleazy's",'GLASGOW'],['17 OCT',"King Tut's",'GLASGOW'],['07 NOV','Mono','GLASGOW'],['22 NOV','Broadcast','GLASGOW']];
function App(){const[page,setPage]=useState('HOME');const[time,setTime]=useState(new Date());useEffect(()=>{const i=setInterval(()=>setTime(new Date()),1000);return()=>clearInterval(i)},[]);
const goto=p=>setPage(p);const pageNo=pages[page];const day=time.toLocaleDateString('en-GB',{weekday:'short',day:'2-digit',month:'short',year:'numeric'});const clock=time.toLocaleTimeString('en-GB',{hour12:false});
return <div className="crt"><header><div className="topline"><span>100</span><span>VELVET 100</span><span>{day}</span><strong>{clock}</strong><span className="grow"/><span>GLASGOW</span><b>16°C</b><span>☀</span></div><div className="head"><div className="logo">VELVET</div><nav>{Object.entries(pages).map(([k,n])=><button key={k} className={page===k?'active':''} onClick={()=>goto(k)}><i>{n}</i> {k}</button>)}</nav></div></header>
<main>
{page==='HOME'&&<Home goto={goto}/>}
{page==='MUSIC'&&<Music/>}
{page==='LIVE'&&<Live/>}
{page==='EPK'&&<EPK/>}
{page==='CONTACT'&&<Contact/>}
</main>
<footer><span>VELVET</span><span>:::</span><span>COME HOME — OUT NOW</span><span>:::</span><span>GLASGOW</span><span>:::</span><span>MUSIC</span><span>:::</span><span>LIVE</span><span>:::</span><span>CONTACT</span><span>:::</span><span>VELVET</span></footer>
</div>}
function Bar({no,title,children}){return <section><div className="bar"><span>{no} {title}</span><span>1/1</span></div>{children}</section>}
function Home({goto}){return <div className="grid home"><div className="left"><Bar no="101" title="HOME"><div className="hero"><div className="halftone"><div className="fakeband">V<br/>V<br/>V<br/>V<br/>V</div></div><div className="heroText"><small>NEW SINGLE</small><h1>COME HOME</h1><h2>OUT NOW</h2><p>LISTEN ON <u>SPOTIFY</u> / <u>APPLE MUSIC</u> / <u>BANDCAMP</u></p></div></div></Bar><Bar no="" title="LISTEN NOW"><div className="listen"><div className="cover">CH</div><div><strong>COME HOME</strong><small>Velvet · Single · 2026</small><div className="track">▶ <span></span> 3:42</div></div><div className="services"><button>◉ SPOTIFY</button><button>♫ APPLE MUSIC</button><button>bc BANDCAMP</button></div></div></Bar><Bar no="" title="SOCIALS"><div className="socials"><a>◎ INSTAGRAM</a><a>♪ TIKTOK</a><a>▶ YOUTUBE</a><a>◉ SPOTIFY</a><a>bc BANDCAMP</a></div></Bar></div><div className="right"><Bar no="102" title="MUSIC"><MiniMusic/></Bar><Bar no="103" title="LIVE"><div className="upcoming">{[['03 OCT',"Nice 'n' Sleazy's"],['17 OCT',"King Tut's"],['07 NOV','Mono'],['22 NOV','Broadcast']].map(g=><div className="gig" key={g[0]}><b>{g[0]}</b><span>{g[1]}<small>GLASGOW</small></span><a onClick={()=>goto('LIVE')}>TICKETS</a></div>)}</div></Bar><Bar no="104" title="PRESS / EPK"><div className="epkMini"><div><h3>ABOUT VELVET</h3><p>Glasgow five-piece making dreamy, guitar-driven indie with hints of noise and melody.</p><a onClick={()=>goto('EPK')}>READ FULL BIO 104 &gt;</a></div><div><h3>QUICK LINKS</h3><p>■ Short bio<br/>■ Long bio<br/>■ Press photos<br/>■ Logos<br/>■ Selected press quotes<br/>■ Previous notable shows<br/>■ Tech rider</p></div></div></Bar><Bar no="105" title="CONTACT"><div className="contactMini"><div><h3>BOOKING & ENQUIRIES</h3><p>booking@velvetband.co.uk<br/>general@velvetband.co.uk</p></div><div><h3>FOLLOW</h3><p>◎　♪　▶　◉　bc</p></div></div></Bar></div></div>}
function MiniMusic(){return <div>{releases.map((r,i)=><div className="release mini" key={r.title}><div className={'cover c'+i}>{r.art}</div><div><strong>{r.title}</strong><small>{r.type} · {r.year}</small><p>SPOTIFY | APPLE MUSIC | BANDCAMP</p></div><b>0{i+1}</b></div>)}<div className="more">More releases 102 &gt;</div></div>}
function Music(){return <div className="single"><Bar no="102" title="MUSIC"><div className="releaseList">{releases.map((r,i)=><div className="release" key={r.title}><div className={'cover c'+i}>{r.art}</div><div><h2>{r.title}</h2><small>{r.type} · {r.year}</small><p>SPOTIFY　|　APPLE MUSIC　|　BANDCAMP</p></div></div>)}</div></Bar></div>}
function Live(){return <div className="single"><Bar no="103" title="LIVE"><h2 className="yellow">UPCOMING GIGS</h2>{gigs.map(g=><div className="bigGig" key={g[0]}><b>{g[0]}</b><div><strong>{g[1]}</strong><small>{g[2]}</small></div><button>TICKETS</button></div>)}<hr/><h2 className="yellow">PAST SHOWS</h2><p>Audio / The Hug & Pint / Nice 'n' Sleazy's / King Tut's / Mono / Broadcast / + more</p></Bar></div>}
function EPK(){return <div className="single"><Bar no="104" title="PRESS / EPK"><div className="two"><div><h2 className="yellow">ABOUT VELVET</h2><p>Velvet are a Glasgow five-piece making dreamy, guitar-driven indie with hints of noise and melody. The current lineup formed in 2019.</p><p>The band have played sold-out shows at Audio, Nice 'n' Sleazy's and King Tut's, released the compilation <i>The Constant</i>, and continue to release new material.</p></div><div><h2 className="yellow">DOWNLOADS / INFO</h2><p>■ Short bio<br/>■ Long bio<br/>■ Press photos<br/>■ Logo pack<br/>■ Music links<br/>■ Previous notable shows<br/>■ Technical rider / stage plot</p></div></div></Bar></div>}
function Contact(){return <div className="single"><Bar no="105" title="CONTACT"><div className="two"><div><h2 className="yellow">BOOKING</h2><p className="bigEmail">booking@velvetband.co.uk</p><h2 className="yellow">GENERAL ENQUIRIES</h2><p className="bigEmail">general@velvetband.co.uk</p></div><div><h2 className="yellow">FOLLOW</h2><p>INSTAGRAM<br/>TIKTOK<br/>YOUTUBE<br/>SPOTIFY<br/>BANDCAMP</p></div></div></Bar></div>}
createRoot(document.getElementById('root')).render(<App/>);